# Generated by Django 2.1.15 on 2022-02-08 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(auto_created=True, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Installation Requested', 'Installation Requested'), ('Installation in Progress', 'Installation in Progress'), ('Installation Complete', 'Installation Complete'), ('Installation Rejected', 'Installation Rejected')], default=('Installation Requested', 'Installation Requested'), max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('install', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.Installation')),
            ],
        ),
    ]
