# Generated by Django 2.1.15 on 2022-03-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_status_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='install',
            new_name='installation',
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
    ]
