# Generated by Django 2.1.15 on 2022-02-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_installation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.AddField(
            model_name='status',
            name='install',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.Installation'),
        ),
    ]
