# Generated by Django 2.1.15 on 2022-02-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Installation Requested', 'Installation Requested'), ('Installation in Progress', 'Installation in Progress'), ('Installation Complete', 'Installation Complete'), ('Installation Rejected', 'Installation Rejected')], default=('Installation Requested', 'Installation Requested'), max_length=255),
        ),
    ]
