# Generated by Django 2.1.15 on 2022-02-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220202_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Installation Requested', 'Installation Requested'), ('Installation in Progress', 'Installation in Progress'), ('Installation Rejected', 'Installation Rejected')], default=('Installation Requested', 'Installation Requested'), max_length=255),
        ),
    ]
